### ISSUE TITLE
Installation from github using devtools, not working

### ISSUE THREAD

**Issue by anubhavdas0907** [mikemc/metacal#20]
Hi Mike,

tried installing the way it is mentioned in the readme.md using devtools. Following was the error.

```
> devtools::install_github("mikemc/metacal")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref master

  Did you spell the repo owner (`mikemc`) and repo name (`metacal`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```

I installed it using the source code and installation was successful.

Cheers !!!
Anubhav

**Comment by mikemc** [comment]
Hi @anubhavdas0907, this works fine for me; I have remotes version 2.4.0 and devtools 2.4.1. My guess is that you are using an out-of-date devtools and/or remotes version (which is what devtools uses to install from github), which I'm guessing is looking for the "master" branch by default, whereas metacal now uses "main" as is becoming standard. If you don't want to upgrade then you can try using the "ref" argument to set the branch to "main".

**Comment by anubhavdas0907** [comment]
Hi Mike,

Thanks for pointing that out. My remotes and devtools versions are older (remotes V 2.1.0, and devtools V 2.2.1).
I have already installed it using the source code, but for next time, I will keep your advice in mind.

Closing the issue.

Thanks again.
